### ISSUE TITLE
Add some convenience properties to dataclasses

### ISSUE THREAD

**Issue by Levi-Lesches** [Levi-Lesches/RamLife#64]
Currently, there are some properties that are technically accessible from the data, but could be more convenient. However, in some contexts, it can be really difficult to get them. Here are those that I found: 

- Section-IDs for subjects -- add `Subject.id`
- Name of the period in the _user's schedule_ -- add `PeriodData.name`
- Name of the day of a period in the user's schedule -- add `PeriodData.dayName`

**Comment by BraydenKO** [comment]
Closed by #80
